### ISSUE TITLE
HOT Projects out of date

### ISSUE THREAD

**Issue by mikelmaron** [hotosm/osm-analytics-cruncher#6] opened 2016-05-24 16:22 UTC
OSMTM project list is out of date (missing Sri Lanka tasks). 

How frequently does this run? https://github.com/hotosm/osm-analytics-cruncher/blob/master/hotprojects.sh

**Comment by dekstop** [comment] 2016-05-24 16:45
From #hot IRC:
  `<dodobas> ok, so the process has been restarted... seems like the maintenerdeveloper updated the job script, but forgot to make it executable :)`
  `<dodobas> anyways... update process starts everyday at 8:15 UTC`

I'm told it takes a long time to run... dodobas estimated 14h, but wasn't entirely sure. So check again in ~12-15h.

(I can't close this issue as a non-maintainer, but the issue is resolved.)

**Closed as completed** 2016-05-24 16:46 UTC

**Comment by tyrasd** [comment] 2016-05-25 07:56
> seems like the maintenerdeveloper updated the job script, but forgot to make it executable

Oops, that must have been me, sorry.

Yeah, updates are run daily and take ~14h or so in total, but results are published as they're ready and updating the HOT TM projects data is the first thing the script does, so they should get updated daily shortly after 8:15 UTC.
